# Generated by Django 2.1.5 on 2019-01-28 14:44

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('users', models.ManyToManyField(blank=True, related_name='rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_timestamp'],
            },
        ),
    ]
