# Generated by Django 2.1.5 on 2019-02-06 08:06

from django.db import migrations, models
import django.db.models.deletion

COLORS = [
    'EB5959', # reddish
    'D1931B', # orange
    '50E3C2', # lightish green
    '26CD69', # green
    '2173D5', # blue
    '4A32AA', # purple
    'BA43BC', # pink
    '3B6BA3', # muddy
]

def create_possible_colors(apps, schema_editor):
    Color = apps.get_model('friends', 'Color')

    for color_id, color_value in enumerate(COLORS, start=1):
        Color.objects.create(id=color_id, hex_value=color_value)

class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lunauser',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='friends.Color'),
        ),
        migrations.RunPython(create_possible_colors)
    ]
