# Generated by Django 2.1.5 on 2019-02-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunauser',
            name='emoji',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
