# Generated by Django 2.1.5 on 2019-02-19 13:59

from django.db import migrations

# color names from https://coolors.co/app
COLORS = [
    'EF5350', # red-orange
    'FFB74D', # pastel orange
    '83D581', # pastel green
    '50E3C2', # turquoise
    '4FC3F7', # maya blue
    '42A5F5', # picton blue
    '9575CD', # dark pastel purple
    'F06292', # light crimson
]

def update_possible_colors(apps, schema_editor):
    Color = apps.get_model('friends', 'Color')

    for color_id, color_value in enumerate(COLORS, start=1):
        new_color = Color.objects.get(id=color_id)
        new_color.hex_value = color_value
        new_color.save()


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_auto_20190213_1016'),
    ]

    operations = [
        migrations.RunPython(update_possible_colors)
    ]
