# Generated by Django 2.1.5 on 2019-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_surveyquestion_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='users',
        ),
        migrations.AlterField(
            model_name='chat',
            name='round',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
