# Generated by Django 2.1.5 on 2019-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_auto_20190221_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='brian_bot',
            field=models.BooleanField(default=False),
        ),
    ]
