# Generated by Django 2.1.5 on 2019-02-21 10:34

from django.db import migrations

# color names from https://coolors.co/app
COLORS = [
    'EF5350', # red-orange
    'FFB74D', # pastel orange
    '83D581', # pastel green
    '50E3C2', # turquoise
    '4FC3F7', # maya blue
    '42A5F5', # picton blue
    '9575CD', # dark pastel purple
    'F06292', # light crimson
]

def create_brian_bot(apps, schema_editor):

    # Delete colours and re-assign with auto-incrementation
    Color = apps.get_model('friends', 'Color')
    Color.objects.all().delete()
    for color in COLORS:
      Color.objects.create(hex_value=color)

    # Add Brian Bot color
    brian_bot_color = Color.objects.create(hex_value='623694', brian_bot=True)

    # Create Brian Bot as first LunaUser
    LunaUser = apps.get_model('friends', 'LunaUser')
    LunaUser.objects.create(
        username='Brian-Bot',
        city='Luminos',
        emoji='⭐',
        color=brian_bot_color,
        is_staff=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_brian_bot_color'),
    ]

    operations = [
        migrations.RunPython(create_brian_bot)
    ]
