# Generated by Django 2.1.5 on 2019-02-25 14:06

from django.db import migrations, models


def update_brian_bot(apps, schema_editor):
    LunaUser = apps.get_model('friends', 'LunaUser')

    # Set is_brian_bot flag to True for brian_bot LunaUser
    brian_bot = LunaUser.objects.get(is_staff=True, username='Brian-Bot')
    brian_bot.is_brian_bot = True
    brian_bot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0012_create_brian_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunauser',
            name='is_brian_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_brian_bot)
    ]
