# Generated by Django 2.1.5 on 2019-02-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0012_create_brian_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',)},
        ),
    ]
