# Generated by Django 2.1.5 on 2019-02-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0013_is_brian_bot_flag'),
        ('friends', '0013_create_feedback_models'),
        ('friends', '0013_messages_descending'),
    ]

    operations = [
    ]
