# Generated by Django 2.1.5 on 2019-02-28 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0014_merge_20190227_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='chat_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='friends.ChatUsers'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='rating_response',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
