# Generated by Django 2.1.5 on 2019-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0015_feedback_response_validations'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatusers',
            name='feedback_requested',
            field=models.BooleanField(default=False),
        ),
    ]
