# Generated by Django 2.1.5 on 2019-03-04 08:05

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    LunaUser = apps.get_model('friends', 'LunaUser')
    for user in LunaUser.objects.all():
        user.notification_id = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0016_chatusers_feedback_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunauser',
            name='notification_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='lunauser',
            name='notification_id',
            field=models.UUIDField(blank=False, default=uuid.uuid4, null=False, unique=True),
        )
    ]
