# Generated by Django 2.1.5 on 2019-03-01 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0016_chatusers_feedback_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Terms of Service'), (2, 'Privacy Policy')])),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserTermsAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.Terms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
