# Generated by Django 2.1.5 on 2019-03-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0018_create_legacy_privacy_policy'),
        ('friends', '0017_lunauser_notification_id'),
    ]

    operations = [
    ]
