# Generated by Django 2.1.5 on 2019-03-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0020_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacydataset',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lunauser',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
